### ISSUE TITLE
Seeds have a bug that doesn't grow

### ISSUE THREAD

**Issue by 167OSS** [LITW-Refined-New-Stories/plantmegapack#2]
When I tested with this branch, I realized that the maple mod's sprinkler didn't work for this mod's plants, and when I switched back to the original mod's version 4.33, it worked fine

**Comment by Pilzinsel64** [comment]
Can you link me the mod please?

**Comment by 167OSS** [comment]
[upzipme.zip](https://github.com/LITW-Refined-New-Stories/plantmegapack/files/14396326/upzipme.zip)

**Comment by 167OSS** [comment]
> [upzipme.zip](https://github.com/LITW-Refined-New-Stories/plantmegapack/files/14396326/upzipme.zip)
These two mods are now unavailable for download from official web

**Comment by Pilzinsel64** [comment]
Ok, I finally moved the changes to a seperated mod using mixins.
See: https://github.com/LITW-Refined-New-Stories/plantmegapackfix/releases

So I archived this repository as it's obsulete now. Due the decompiled code it can have possible incompatibility with other mods or new bugs I just don't know yet.

Use the fix mod linked above together with the latest public version of PMP.
